Repository openhwgroup/core-v-verif, pull requests merged in 2024-02, with the labels that each got.

#2367 Merge cv32e40s/release <-- cv32e40s/dev
  bin/merge.sh
  cv32e40s/docs/VerifPlans/Simulation/interrupts/CV32E40SX_CLIC.csv
  cv32e40s/docs/VerifPlans/Simulation/interrupts/CV32E40SX_CLIC.json
  cv32e40s/docs/VerifPlans/Simulation/interrupts/CV32E40SX_CLIC.xlsx
  cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
  cv32e40s/regress/cv32e40s_full.yaml
  cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_sl_trigger_match.sv
  cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
  cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv
  cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_data_independent_timing_assert.sv
  cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
  cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_hardened_pc_assert.sv
  cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv
  cv32e40s/tests/cfg/pma_test_cfg_2_clic.yaml
  cv32e40s/tests/programs/custom/clic/clic.c
  cv32e40s/tests/programs/custom/mhpmcounter_write_test/test.yaml
  cv32e40s/tests/programs/custom/minhv_pma_block/minhv_pma_block.c
  cv32e40s/tests/programs/custom/minhv_pma_block/test.yaml
  lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
Labels: cv32e40s

#2366 [Xcelium support] Remove void from DPI definition
  lib/uvm_agents/uvma_axi/src/uvma_axi_pkg.sv
Labels: cva6

#2365 [Xcelium support] Bugfix uvm sysverilog compliant
  lib/uvm_agents/uvma_axi/src/comps/uvma_axi_seq_item_logger.sv
  lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_assert.sv
  lib/uvm_agents/uvma_rvfi/uvma_rvfi_agent.sv
  lib/uvm_components/uvmc_rvfi_reference_model/uvmc_rvfi_reference_model.sv
  lib/uvm_components/uvmc_rvfi_scoreboard/uvmc_rvfi_scoreboard.sv
Labels: cva6

#2376 Using CORE-V-VERIF relative paths instead of Makefile relative paths
  mk/uvmt/xrun.mk
Labels: cv32e40x

#2368 Adding make targets needed to run riscof arch-tests for cv32e40x
  bin/clonetb
  mk/Common.mk
  mk/riscof.mk
  mk/uvmt/uvmt.mk
  mk/uvmt/xrun.mk
Labels: cv32e40x

#2380 Coverage analysis update and new regress features for shell script generation
  bin/lib/cv_regression.py
  bin/templates/regress_sh.j2
  bin/templates/regress_vsif.j2
  cv32e40p/env/corev-dv/cv32e40p_instr_sequence.sv
  cv32e40p/env/corev-dv/instr_lib/cv32e40p_float_instr_lib.sv
  cv32e40p/env/corev-dv/instr_lib/cv32e40p_instr_for_func_cvg_lib.sv
  cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_hwloop_instr_lib.sv
  cv32e40p/env/uvme/cov/uvme_debug_covg.sv
  cv32e40p/env/uvme/cov/uvme_interrupt_covg_v2.sv
  cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
  cv32e40p/regress/README.md
  cv32e40p/regress/cv32e40pv2_for_func_cvg_improvement.yaml
  cv32e40p/regress/cv32e40pv2_interrupt_debug.yaml
  cv32e40p/regress/cv32e40pv2_interrupt_debug_short.yaml
  cv32e40p/sim/tools/vsim/exclusion/README
  cv32e40p/sim/tools/vsim/exclusion/cv32e40pv2_code_all_cfg_waiver.do
  cv32e40p/sim/tools/vsim/exclusion/cv32e40pv2_code_pulp_cfg_waiver.do
  cv32e40p/sim/tools/vsim/exclusion/cv32e40pv2_func_asrt_n_directive_waiver.do
  cv32e40p/sim/tools/vsim/exclusion/cv32e40pv2_func_uvme_debug_waiver.do
  cv32e40p/sim/tools/vsim/exclusion/cv32e40pv2_func_uvme_interrupt_waiver.do
  cv32e40p/sim/tools/vsim/exclusion/pulp/exclusion.do
  cv32e40p/sim/tools/vsim/exclusion/pulp_fpu/exclusion.do
  cv32e40p/tb/uvmt/uvmt_cv32e40p_macros.sv
  cv32e40p/tb/uvmt/uvmt_cv32e40p_tb.sv
  cv32e40p/tests/programs/corev-dv/corev_directed_for_hwloop_covg_test/corev-dv.yaml
  cv32e40p/tests/programs/corev-dv/corev_directed_for_hwloop_covg_test/test.yaml
  cv32e40p/tests/programs/corev-dv/corev_rand_fp_instr_debug/corev-dv.yaml
  cv32e40p/tests/programs/corev-dv/corev_rand_fp_instr_debug/test.yaml
  cv32e40p/tests/uvmt/compliance-tests/uvmt_cv32e40p_firmware_test.sv
  mk/Common.mk
  mk/uvmt/uvmt.mk
Labels: cv32e40p
