Repository openhwgroup/core-v-verif, pull requests merged in 2024-11, with the labels that each got.

#2552 Updated cv dv utils for VCS
  lib/cv_dv_utils/uvm/Files.f
  lib/cv_dv_utils/uvm/bp_gen/bp_vif.sv
  lib/cv_dv_utils/uvm/clock_gen/clock_driver_c.svh
  lib/cv_dv_utils/uvm/clock_mon/xrtl_clock_mon_vif.sv
  lib/cv_dv_utils/uvm/memory_rsp_model/memory_response_if.sv
  lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_agent.sv
  lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_drv.sv
  lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_mon.sv
  lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_vsqr.sv
  lib/uvm_agents/uvma_axi5/src/obj/uvma_axi_cfg.sv
  lib/uvm_agents/uvma_axi5/src/obj/uvma_axi_cntxt.sv
  lib/uvm_agents/uvma_axi5/src/seq/uvma_axi_base_seq.sv
  lib/uvm_agents/uvma_axi5/src/seq/uvma_axi_mst_seq.svh
  lib/uvm_agents/uvma_axi5/src/seq/uvma_axi_slv_seq.sv
  lib/uvm_agents/uvma_axi5/src/uvma_axi_intf.sv
  lib/uvm_agents/uvma_axi5/src/uvma_axi_macros.sv
  lib/uvm_agents/uvma_axi5/src/uvma_axi_pkg.sv
Labels: Common Infrastructure

#2553 [Spike] Set default PMP granularity to 8. Add support for corresponding Yaml parameter.
  vendor/patches/riscv/riscv-isa-sim/0035-increase-pmp-granularity-to-8.patch
  vendor/riscv/riscv-isa-sim/riscv/Proc.cc
  vendor/riscv/riscv-isa-sim/riscv/processor.cc
Labels: cva6, Common Infrastructure

#2556 CEA AXI update with correction for VCS
  lib/uvm_agents/uvma_axi5/src/obj/uvma_axi_cfg.sv
  lib/uvm_agents/uvma_axi5/src/seq/uvma_axi_base_seq.sv
  lib/uvm_agents/uvma_axi5/src/seq/uvma_axi_mst_seq.svh
  lib/uvm_agents/uvma_axi5/src/seq/uvma_axi_transaction.sv
  lib/uvm_agents/uvma_axi5/src/uvma_axi_intf.sv
  lib/uvm_agents/uvma_axi5/src/uvma_axi_macros.sv
Labels: Common Infrastructure: UVM Agent
